
[program:pllmond]
command=/opt/mcc-board-cli/bin/pllmond.py
stdout_logfile=/var/log/pllmond-stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=5
stderr_logfile=/var/log/pllmond-stderr.log
stderr_ogfile_maxbytes=1MB
stderr_logfile_backups=5
autorestart=true
startsecs=5

